[tool.poetry]
name = "refactoredexample"
version = "0.1.0"
description = ""
authors = ["Tyler Thompson <tylert123@yahoo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flake8 = "^6.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
